### ISSUE TITLE
使用abp cli 生成一个app，再生成一个新的module，代码生成器失效

### ISSUE THREAD

**Issue by indexlang** [EasyAbp/AbpHelper.GUI#132]
GUI版本V2.3.2
使用abp cli生成项目和模块A，结构如图：
![image](https://user-images.githubusercontent.com/6028356/200461901-528d934e-9e56-4779-baa2-be89adfc4511.png)
使用GUI CRUD代码出错，不执行任何操作：
2022-11-08 10:30:36.742 +08:00 [ERR] Error while invoking activity activity-5 of workflow 5d2715022e9345c7bb2ac427cd86c524
System.IO.FileNotFoundException: The solution file 'ModuleA.sln' is not found in 'H:\App-main'. Make sure you specific the right folder.
   at EasyAbp.AbpHelper.Core.Steps.Abp.ProjectInfoProviderStep.EnsureSlnFileExists(WorkflowExecutionContext context, String projectName) in D:\a\AbpHelper.GUI\AbpHelper.GUI\AbpHelper.CLI\src\AbpHelper.Core\Steps\Abp\ProjectInfoProviderStep.cs:line 94
   at EasyAbp.AbpHelper.Core.Steps.Abp.ProjectInfoProviderStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\a\AbpHelper.GUI\AbpHelper.GUI\AbpHelper.CLI\src\AbpHelper.Core\Steps\Abp\ProjectInfoProviderStep.cs:line 71
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
2022-11-08 10:30:36.743 +08:00 [ERR] Error activity: {
  "Name": null
}

**Comment by gdlcf88** [comment]
AbpHelper only supports the startup-template-based solution structure. But I think you can try to specify your directory. See: https://github.com/EasyAbp/AbpHelper.CLI/blob/7624ad81faf6b0d83956a3fc7dedf1b506a68ad3/src/AbpHelper.Core/Commands/CommandOptionsBase.cs#L6
