### ISSUE TITLE
2.10生成代码报错

### ISSUE THREAD

**Issue by sysnlee** [EasyAbp/AbpHelper.GUI#168]
配置过解决方案地址，输入实体名称后，报错：

```
2023-10-31 08:56:10.272 +08:00 [ERR] An exception was thrown while activating Volo.Abp.ObjectMapping.DefaultObjectMapper -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor -> λ:AutoMapper.IMapper -> λ:AutoMapper.IConfigurationProvider.‘
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.ObjectMapping.DefaultObjectMapper -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor -> λ:AutoMapper.IMapper -> λ:AutoMapper.IConfigurationProvider.
 ---> AutoMapper.AutoMapperConfigurationException: 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
======================================================================================================================================================================
AbpHelperGenerateAppServiceMethodsInput -> MethodsCommandOption (Destination member list)
EasyAbp.AbpHelper.Gui.CodeGeneration.AppService.Dtos.AbpHelperGenerateAppServiceMethodsInput -> EasyAbp.AbpHelper.Core.Commands.Generate.Methods.MethodsCommandOption (Destination member list)

Unmapped properties:
IntegrationService
=====================================================================================================================================================================
AbpHelperGenerateControllerInput -> ControllerCommandOption (Destination member list)
EasyAbp.AbpHelper.Gui.CodeGeneration.Controller.Dtos.AbpHelperGenerateControllerInput -> EasyAbp.AbpHelper.Core.Commands.Generate.Controller.ControllerCommandOption (Destination member list)

Unmapped properties:
IntegrationService

   at Volo.Abp.AutoMapper.AbpAutoMapperModule.<>c.<ConfigureServices>b__1_0(IServiceProvider sp)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.<>c__DisplayClass3_0.<Register>b__0(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Volo.Abp.Application.Services.ApplicationService.<get_ObjectMapper>b__24_0(IServiceProvider provider)
   at Volo.Abp.DependencyInjection.CachedServiceProviderBase.<>c__DisplayClass11_0.<GetService>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Volo.Abp.DependencyInjection.CachedServiceProviderBase.GetService(Type serviceType, Func`2 factory)
   at Volo.Abp.DependencyInjection.CachedServiceProviderBase.GetService[T](Func`2 factory)
   at Volo.Abp.DependencyInjection.AbpLazyServiceProvider.LazyGetService[T](Func`2 factory)
   at Volo.Abp.Application.Services.ApplicationService.get_ObjectMapper()
   at EasyAbp.AbpHelper.Gui.CodeGeneration.Crud.CodeGenerationCrudAppService.GenerateAsync(AbpHelperGenerateCrudInput input) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\CodeGeneration\Crud\CodeGenerationCrudAppService.cs:line 19
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.CodeGeneration.Components.Crud.GenerateCrudCode.InternalExecuteAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\CodeGeneration\Components\Crud\GenerateCrudCode.razor.cs:line 14
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.Shared.ExecutableComponentBase.ExecuteAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\Shared\ExecutableComponentBase.cs:line 30
2023-10-31 08:56:10.273 +08:00 [ERR] ---------- Exception Data ----------
ActivatorChain = Volo.Abp.ObjectMapping.DefaultObjectMapper -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor -> λ:AutoMapper.IMapper -> λ:AutoMapper.IConfigurationProvider
````
应该是少个对象转换配置吧，我是菜鸟，也不知道怎么玩转github

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/AbpHelper.GUI/releases/tag/v2.10.1
