### ISSUE TITLE
dropdowns click led to This application may no longer respond until reloaded.

### ISSUE THREAD

**Issue by sadiqsalim** [EasyAbp/AbpHelper.GUI#178]
When I click on the dropdowns, for example, NoSolution to add a solution, the program will freeze and I have to reload it, same problem with the logs dropdown. (I'm using Win10)

The Show Log shows the following error:
2024-05-31 21:36:47.213 +03:00 [ERR] Unhandled exception in circuit 'HG6yHG05saIk7wisVtgNQzYrT7IwTQWiXfjliD9aUgM'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.BarItem.OnDropdownVisible()
   at Blazorise.BarDropdown.SetVisibleState(Boolean visible)
   at Blazorise.BarDropdown.Toggle(String dropdownToggleElementId)
   at Blazorise.BarDropdownToggle.ClickHandler(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by khaledpro2012** [comment]
I have same error in last version

**Comment by nacho-gonzalez** [comment]
Hi, same issue here with ABP v8.1.3 and AbpHelper GUI v2.12.0.
I tried to debug it but faced the following error building the application:
`The type or namespace name 'Workflow' does not exist in the namespace 'EasyAbp.AbpHelper.Core' (are you missing an assembly reference?)	AbpHelper.Core	...\EasyAbp\AbpHelper.GUI\AbpHelper.CLI\src\AbpHelper.Core\Commands\Generate\Methods\MethodsCommand.cs	8	
`
I downloaded it manually but I was not able to make the solution working :(

**Comment by gdlcf88** [comment]
Caused by https://github.com/abpframework/abp/issues/19405.

**Comment by nacho-gonzalez** [comment]
What delay??? :) Tried and working fine! thank you!
