### ISSUE TITLE
EasyAbp.AbpHelper.GUI创建应用后弹出的“恭喜”界面点击“好”无法关闭

### ISSUE THREAD

**Issue by sysnlee** [EasyAbp/AbpHelper.GUI#190]
![image](https://github.com/user-attachments/assets/44c53abe-5d30-4b00-ad9b-630bfc02af9d)
点击弹窗无法关闭，查看的日志如下：
```
2024-09-16 21:12:45.300 +08:00 [INF] Creating your project...
2024-09-16 21:12:45.300 +08:00 [INF] Project name: epo
2024-09-16 21:12:45.300 +08:00 [INF] Template: app
2024-09-16 21:12:45.300 +08:00 [INF] Tiered: yes
2024-09-16 21:12:45.301 +08:00 [INF] Version: 8.2.1
2024-09-16 21:12:45.301 +08:00 [INF] Database provider: EntityFrameworkCore
2024-09-16 21:12:45.301 +08:00 [INF] DBMS: MySQL
2024-09-16 21:12:45.302 +08:00 [INF] UI Framework: Angular
2024-09-16 21:12:45.302 +08:00 [INF] Public Web Site: yes
2024-09-16 21:12:45.302 +08:00 [INF] Mobile App: ReactNative
2024-09-16 21:12:45.303 +08:00 [INF] Output folder: C:\Users\leishen\AppData\Local\Programs\abphelper-gui\dotnet\EasyAbp.AbpHelper.Gui.Blazor\eposrc\epo
2024-09-16 21:12:45.582 +08:00 [INF] Start processing HTTP request GET https://abp.io/api/download/all-versions?includePreReleases=true
2024-09-16 21:12:45.582 +08:00 [INF] Sending HTTP request GET https://abp.io/api/download/all-versions?includePreReleases=true
2024-09-16 21:12:47.055 +08:00 [INF] Received HTTP response headers after 1472.7761ms - 200
2024-09-16 21:12:47.055 +08:00 [INF] End processing HTTP request after 1473.0688ms - 200
2024-09-16 21:12:47.066 +08:00 [INF] Start processing HTTP request POST https://abp.io/api/download/template/get-nuget-version/
2024-09-16 21:12:47.066 +08:00 [INF] Sending HTTP request POST https://abp.io/api/download/template/get-nuget-version/
2024-09-16 21:12:47.475 +08:00 [INF] Received HTTP response headers after 409.1817ms - 200
2024-09-16 21:12:47.475 +08:00 [INF] End processing HTTP request after 409.4355ms - 200
2024-09-16 21:12:47.478 +08:00 [INF] Using cached template: app, version: 8.2.1
2024-09-16 21:12:47.483 +08:00 [INF] Theme: Basic
2024-09-16 21:12:47.483 +08:00 [WRN] You may need to make some additional changes for this theme. See the documentation for more information: https://abp.io/docs/latest/framework/ui/angular/theme-configurations
2024-09-16 21:12:47.490 +08:00 [INF] Start processing HTTP request GET https://abp.io/api/license/api-key
2024-09-16 21:12:47.490 +08:00 [INF] Sending HTTP request GET https://abp.io/api/license/api-key
2024-09-16 21:12:47.885 +08:00 [INF] Received HTTP response headers after 394.669ms - 200
2024-09-16 21:12:47.885 +08:00 [INF] End processing HTTP request after 394.9422ms - 200
2024-09-16 21:12:48.210 +08:00 [INF] Check out the documents at https://abp.io/docslatest/solution-templates/layered-web-application
2024-09-16 21:12:48.219 +08:00 [INF] Start processing HTTP request POST https://abp.io/api/clianalytics/collect
2024-09-16 21:12:48.219 +08:00 [INF] Sending HTTP request POST https://abp.io/api/clianalytics/collect
2024-09-16 21:12:48.605 +08:00 [INF] Received HTTP response headers after 386.3644ms - 204
2024-09-16 21:12:48.605 +08:00 [INF] End processing HTTP request after 386.6242ms - 204
2024-09-16 21:12:48.789 +08:00 [INF] 'epo' has been successfully created to 'C:\Users\leishen\AppData\Local\Programs\abphelper-gui\dotnet\EasyAbp.AbpHelper.Gui.Blazor\eposrc\epo'
2024-09-16 21:12:48.798 +08:00 [INF] Creating initial migrations...
2024-09-16 21:13:00.858 +08:00 [INF] Initial migrations are created.
2024-09-16 21:13:00.859 +08:00 [INF] Installing client-side packages...
2024-09-16 21:13:02.568 +08:00 [INF] Found 2 projects.
2024-09-16 21:13:02.568 +08:00 [INF] C:\Users\leishen\AppData\Local\Programs\abphelper-gui\dotnet\EasyAbp.AbpHelper.Gui.Blazor\eposrc\epo\angular
2024-09-16 21:13:02.568 +08:00 [INF] C:\Users\leishen\AppData\Local\Programs\abphelper-gui\dotnet\EasyAbp.AbpHelper.Gui.Blazor\eposrc\epo\aspnet-core\src\epo.HttpApi.Host
2024-09-16 21:13:02.830 +08:00 [INF] Running Yarn on C:\Users\leishen\AppData\Local\Programs\abphelper-gui\dotnet\EasyAbp.AbpHelper.Gui.Blazor\eposrc\epo\angular
2024-09-16 21:14:53.404 +08:00 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
2024-09-16 21:14:53.410 +08:00 [INF] Start processing HTTP request GET https://raw.githubusercontent.com/EasyAbp/ModuleLibrary/v2/index.json
2024-09-16 21:14:53.410 +08:00 [INF] Sending HTTP request GET https://raw.githubusercontent.com/EasyAbp/ModuleLibrary/v2/index.json
2024-09-16 21:14:55.343 +08:00 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
2024-09-16 21:14:56.098 +08:00 [INF] Received HTTP response headers after 2688.0085ms - 200
2024-09-16 21:14:56.098 +08:00 [INF] End processing HTTP request after 2688.3394ms - 200
2024-09-16 21:14:56.303 +08:00 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
2024-09-16 21:14:58.547 +08:00 [INF] Running Yarn on C:\Users\leishen\AppData\Local\Programs\abphelper-gui\dotnet\EasyAbp.AbpHelper.Gui.Blazor\eposrc\epo\aspnet-core\src\epo.HttpApi.Host
2024-09-16 21:15:20.774 +08:00 [WRN] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyAbp.AbpHelper.Core.Services.ListPackageService.GetInstalledPackagesAsync(String baseDirectory) in D:\a\AbpHelper.GUI\AbpHelper.GUI\AbpHelper.CLI\src\AbpHelper.Core\Services\ListPackageService.cs:line 31
   at EasyAbp.AbpHelper.Gui.Solutions.SolutionAppService.GetPackageDictionaryAsync(GetPackageDictionaryInput input) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\Solutions\SolutionAppService.cs:line 102
   at EasyAbp.AbpHelper.Gui.Blazor.Services.InstalledModulesLookupService.GetAsync(SolutionDto solutionDto) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Services\InstalledModulesLookupService.cs:line 21
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.BuildAppProjectsInstalledModuleNamesAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 124
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.RebuildModulesDataAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 95
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.OnInitializedAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 48
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-09-16 21:15:20.776 +08:00 [ERR] Unhandled exception in circuit 'Y0GAlm9CpYYcaL5gXvkAeRHU035IzmSGixS3zp_gXmA'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyAbp.AbpHelper.Core.Services.ListPackageService.GetInstalledPackagesAsync(String baseDirectory) in D:\a\AbpHelper.GUI\AbpHelper.GUI\AbpHelper.CLI\src\AbpHelper.Core\Services\ListPackageService.cs:line 31
   at EasyAbp.AbpHelper.Gui.Solutions.SolutionAppService.GetPackageDictionaryAsync(GetPackageDictionaryInput input) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\Solutions\SolutionAppService.cs:line 102
   at EasyAbp.AbpHelper.Gui.Blazor.Services.InstalledModulesLookupService.GetAsync(SolutionDto solutionDto) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Services\InstalledModulesLookupService.cs:line 21
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.BuildAppProjectsInstalledModuleNamesAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 124
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.RebuildModulesDataAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 95
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.OnInitializedAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 48
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-09-16 21:15:20.796 +08:00 [INF] Executed endpoint '/_blazor'
2024-09-16 21:15:20.796 +08:00 [INF] Request finished HTTP/2 CONNECT https://localhost:44313/_blazor?id=mSNrenAj6omLWzRFy1IywA - 200 null null 286689.8335ms
2024-09-16 21:15:20.797 +08:00 [INF] Connection id "0HN6MA3P69CRL", Request id "0HN6MA3P69CRL:0000000F": the application completed without reading the entire request body.
```

**Comment by blackWins** [comment]
由于请求[EasyAbp模块列表](https://raw.githubusercontent.com/EasyAbp/ModuleLibrary/v2/index.json)异常导致UI线程阻塞，可关闭窗口并重新唤起尝试恢复。
