### ISSUE TITLE
Could not find a part of the path 'C:\Users\45079\.abp\cli\computer-id.bin'.

### ISSUE THREAD

**Issue by baiqiaw** [EasyAbp/AbpHelper.GUI#195]
创建MAUI应用抛出如下异常：

> ```
2024-11-16 11:50:41.971 +08:00 [ERR] Could not find a part of the path 'C:\Users\45079\.abp\cli\computer-id.bin'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\45079\.abp\cli\computer-id.bin'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Volo.Abp.Cli.ProjectBuilding.Analyticses.CliAnalyticsCollect.CollectAsync(CliAnalyticsCollectInputDto input)
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args)
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs)
   at EasyAbp.AbpHelper.Gui.AbpCli.New.AbpCliNewAppService.CreateMauiAsync(AbpNewMauiInput input) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\AbpCli\New\AbpCliNewAppService.cs:line 57
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.AbpCli.Components.New.CreateMaui.InternalExecuteAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\AbpCli\Components\New\CreateMaui.razor.cs:line 21
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.Shared.ExecutableComponentBase.ExecuteAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\Shared\ExecutableComponentBase.cs:line 30

```

**Comment by baiqiaw** [comment]
已经安装了abp cli
