### ISSUE TITLE
CRUD Code generator Error

### ISSUE THREAD

**Issue by indexlang** [EasyAbp/AbpHelper.GUI#30]
there is a error when I run the generator
new project
and a simple entity
public class AssessmentDepartment : Entity<int>
    {
        public virtual string Name { get; private set; }
        public virtual string PlusInfo { get; private set; }        
    }
the Log:
`[17:00:19 DBG] FileFinderStep Input [searchFileName]: 'AgriCAMVCMenuContributor.cs'
[17:00:19 DBG] FileFinderStep Input [errorIfNotFound]: 'True'
[17:00:20 ERR] Error while invoking activity activity-55 of workflow f82bd7aa9a9a4f5eb127d501cc8943d3
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at EasyAbp.AbpHelper.Steps.Common.FileFinderStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in /home/runner/work/AbpHelper.CLI/AbpHelper.CLI/src/AbpHelper/Steps/Common/FileFinderStep.cs:line 49
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
[17:00:20 ERR] Error activity: {
  "SearchFileName": {
    "Syntax": "JavaScript",
    "Expression": "`${ProjectInfo.Name}MenuContributor.cs`",
    "Type": "System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
  },
  "Name": null
}
`

**Comment by wakuflair** [comment]
You may have multiple `AgriCAMVCMenuContributor.cs` files.
Delete unused files or use `--excude` option to exclude search folders.
