### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Yoshuwa** [EasyAbp/AbpHelper.GUI#32]
Firstly this a great tool, however, I'm getting the following server error when I excute and generate a project

[14:17:22 INF] Downloading template: app, version: 1.0
Error occured while downloading source-code from https://abp.io/api/download/template/ : Remote server returns '500-Internal Server Error'. 
[14:17:26 ERR] Remote server returns '500-Internal Server Error'. 
System.Exception: Remote server returns '500-Internal Server Error'. 
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 44
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 222
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource, Boolean includePreReleases) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 108
   at Volo.Abp.Cli.ProjectBuilding.TemplateProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 56
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 134
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

**Comment by gdlcf88** [comment]
> Error occured while downloading source-code from https://abp.io/api/download/template/ : Remote server returns '500-Internal Server Error'.

Maybe there is something wrong with Volosoft's server, please try to reproduce this problem by using ABP CLI directly, see https://docs.abp.io/en/abp/latest/CLI

**Comment by Yoshuwa** [comment]
> > Error occured while downloading source-code from https://abp.io/api/download/template/ : Remote server returns '500-Internal Server Error'.
> 
> Maybe there is something wrong with Volosoft's server, please try to reproduce this problem by using ABP CLI directly, see https://docs.abp.io/en/abp/latest/CLI

https://docs.abp.io/en/abp/latest/CLI seems to be down.. for now
