### ISSUE TITLE
Generate CRUD with separate dtos occur error

### ISSUE THREAD

**Issue by GerryGe** [EasyAbp/AbpHelper.GUI#41]
Version 0.7.0

![image](https://user-images.githubusercontent.com/6952917/102705195-afc45b00-42bf-11eb-95fa-bc891f0236df.png)

[16:25:33 DBG] Build started...
[16:25:47 DBG] Build failed. Use dotnet build to see the errors.
[16:25:47 ERR] Error while invoking activity activity-79 of workflow 073e6e98ab6d48d39e740909c392cb1a
EasyAbp.AbpHelper.Steps.Common.RunningCommandFailedException: Exception of type 'EasyAbp.AbpHelper.Steps.Common.RunningCommandFailedException' was thrown.
   at EasyAbp.AbpHelper.Steps.Common.RunCommandStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\Repos\EasyAbp\AbpHelper.CLI\src\AbpHelper\Steps\Common\RunCommandStep.cs:line 28
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
[16:25:47 ERR] Error activity: {
  "Command": {
    "Syntax": "JavaScript",
    "Expression": "`dotnet ef migrations add Added${EntityInfo.Name} -p \"${MigrationProjectFile}\" -s \"${StartupProjectFile}\"`",
    "Type": "System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
  },
  "Name": "AddMigration"
}

**Comment by wakuflair** [comment]
It seems there are build errors.
Can you paste the error details?
