### ISSUE TITLE
Version 1.2.0 , Javascript Error on Mac Air 2017 ,i5 X86 ,double core CPU,8GB ram,128ssd

### ISSUE THREAD

**Issue by HillCat** [EasyAbp/AbpHelper.GUI#65]
Uncaught Exception:
Error: spawn dotnet ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

when downloading the Version on my mac computer, double click the dmg package try to install, it popup an error message shows above.

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/AbpHelper.GUI/issues/55
