### ISSUE TITLE
Error about the "settings.ui" module

### ISSUE THREAD

**Issue by beefsteak** [EasyAbp/AbpHelper.GUI#74]
Download the latest version of ABP Framework 4.3，The project will not run after downloading the settingUI module using abphelper tool

System.TypeLoadException: Could not load type 'Volo.Abp.Authorization.Permissions.PermissionDefinition' from assembly 'Volo.Abp.Authorization, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_Signature()
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Castle.DynamicProxy.Generators.MethodSignatureComparer.GetHashCode(MethodInfo obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Add(TElement value)
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Castle.DynamicProxy.Generators.MethodFinder.GetAllInstanceMethods(Type type, BindingFlags flags)
   at Castle.DynamicProxy.Contributors.MembersCollector.CollectMethods(IProxyGenerationHook hook)
   at Castle.DynamicProxy.Contributors.MembersCollector.CollectMembersToProxy(IProxyGenerationHook hook)
   at Castle.DynamicProxy.Contributors.ClassProxyTargetContributor.CollectElementsToProxyInternal(IProxyGenerationHook hook)+MoveNext()
   at Castle.DynamicProxy.Contributors.CompositeTypeContributor.CollectElementsToProxy(IProxyGenerationHook hook, MetaType model)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass33_0.<ObtainProxyType>b__0(CacheKey _)
   at Castle.Core.Internal.SynchronizedDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Autofac.Extras.DynamicProxy.RegistrationExtensions.EnableClassInterceptors[TLimit,TConcreteReflectionActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registration, ProxyGenerationOptions options, Type[] additionalInterfaces)
   at Autofac.Extras.DynamicProxy.RegistrationExtensions.EnableClassInterceptors[TLimit,TConcreteReflectionActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registration)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.AddInterceptors[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, Type serviceType, IEnumerable`1 interceptors)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.InvokeRegistrationActions[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, ServiceRegistrationActionList registrationActionList, Type serviceType, Type implementationType)
   at Autofac.Builder.AbpRegistrationBuilderExtensions.ConfigureAbpConventions[TLimit,TActivatorData,TRegistrationStyle](IRegistrationBuilder`3 registrationBuilder, IModuleContainer moduleContainer, ServiceRegistrationActionList registrationActionList)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Register(ContainerBuilder builder, IServiceCollection services, Object lifetimeScopeTagForSingletons)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Populate(ContainerBuilder builder, IServiceCollection services, Object lifetimeScopeTagForSingletons)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.Populate(ContainerBuilder builder, IServiceCollection services)
   at Volo.Abp.Autofac.AbpAutofacServiceProviderFactory.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at BookStoreDemo.Web.Program.Main(String[] args) in D:\BookStoreDemo\src\BookStoreDemo.Web\Program.cs:line 31

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/115840861-b8d05f00-a44e-11eb-9e7c-9008c7a4d1bb.png)

https://github.com/EasyAbp/Abp.SettingUi/blob/master/Directory.Build.props

Before installing the module, you need to make sure that it is the same ABP version as the version of your application.
