### ISSUE TITLE
CRUD代码生成器不支持仓储有多个上下文

### ISSUE THREAD

**Issue by zhuang51611** [EasyAbp/AbpHelper.GUI#83]
![image](https://user-images.githubusercontent.com/16551215/120051654-08a8d400-c054-11eb-98eb-eefb37b896c5.png)
![image](https://user-images.githubusercontent.com/16551215/120051788-ae5c4300-c054-11eb-883f-9ede182985f1.png)

如图,如果我的仓储有定义了多个上下文,我多次使用EasyAbp 生成器 他提示生成成功,但是业务层和业务抽象层没有添加类...它并没有报错..这个问题困扰我很久 后面发现只要我保留一个上下文就可以正确生成代码

**Comment by wakuflair** [comment]
应该有报错的, 看一下详细的LOG

**Comment by zhuang51611** [comment]
2021-05-29 18:57:55.880 +08:00 [ERR] An exception was thrown while activating Castle.Proxies.TokenCleanupServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.TokenCleanupServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'Castle.Proxies.TokenCleanupServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.IdentityServer.Grants.IPersistentGrantRepository persistentGrantRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.IdentityServer.Grants.IPersistentGrantRepository, Volo.Abp.IdentityServer.Devices.IDeviceFlowCodesRepository, Volo.Abp.Timing.IClock, Microsoft.Extensions.Options.IOptions`1[Volo.Abp.IdentityServer.Tokens.TokenCleanupOptions])'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass35_0.<OnPreparing>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CoreEventMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Volo.Abp.IdentityServer.Tokens.TokenCleanupBackgroundWorker.DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
   at Volo.Abp.BackgroundWorkers.AsyncPeriodicBackgroundWorkerBase.DoWorkAsync()
2021-05-29 18:57:55.880 +08:00 [ERR] ---------- Exception Data ----------
ActivatorChain = Castle.Proxies.TokenCleanupServiceProxy

**Comment by zhuang51611** [comment]
2021-06-02 13:59:53.716 +08:00 [ERR] Parsing entity failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyAbp.AbpHelper.Core.Steps.Abp.EntityParserStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken)
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
2021-06-02 13:59:53.716 +08:00 [ERR] Error while invoking activity activity-8 of workflow 3fc0883c7b8c41f8a555216807e8b5f5
System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyAbp.AbpHelper.Core.Steps.Abp.EntityParserStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken)
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
2021-06-02 13:59:53.727 +08:00 [ERR] Error activity: {
  "Name": null
}
