### ISSUE TITLE
Windows 10 运行错误

### ISSUE THREAD

**Issue by momostarsky** [EasyAbp/AbpHelper.GUI#92]
2021-08-18 14:35:27.792 +08:00 [ERR] Unhandled exception in circuit 'LqtgAT3emcw1zAa7F4iZgqpwKrlD2_VFtCTsXkLDCvw'.
System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。 (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at EasyAbp.AbpHelper.Gui.ModuleManagement.Explorer.ModuleManagementExplorerAppService.RequestModuleGroupListFromSourceAsync(ModuleLibrarySourceDto source) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\ModuleManagement\Explorer\ModuleManagementExplorerAppService.cs:line 75
   at EasyAbp.AbpHelper.Gui.ModuleManagement.Explorer.ModuleManagementExplorerAppService.<>c__DisplayClass7_0.<<GetModuleGroupList>b__0>d.MoveNext() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\ModuleManagement\Explorer\ModuleManagementExplorerAppService.cs:line 63
--- End of stack trace from previous location ---
   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token)
   at EasyAbp.AbpHelper.Gui.ModuleManagement.Explorer.ModuleManagementExplorerAppService.GetModuleGroupList(ModuleLibrarySourceDto source) in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\ModuleManagement\Explorer\ModuleManagementExplorerAppService.cs:line 62
   at EasyAbp.AbpHelper.Gui.ModuleManagement.Explorer.ModuleManagementExplorerAppService.GetModuleGroupListAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Application\ModuleManagement\Explorer\ModuleManagementExplorerAppService.cs:line 44
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.BuildModuleGroupsAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 115
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.RebuildModulesDataAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 91
   at EasyAbp.AbpHelper.Gui.Blazor.Pages.ModuleManagement.Components.Explorer.OnInitializedAsync() in D:\a\AbpHelper.GUI\AbpHelper.GUI\dotnet\src\EasyAbp.AbpHelper.Gui.Blazor\Pages\ModuleManagement\Components\Explorer.razor.cs:line 46
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)[
![1629269684(1)](https://user-images.githubusercontent.com/75593784/129851940-ec8fcdaa-ee45-4057-ad3a-106051480dfb.jpg)
](url)

**Comment by gdlcf88** [comment]
Try to use a VPN.
